### ISSUE TITLE
copy doesn't copy data byte for byte

### ISSUE THREAD

**Issue by alexcb** [kaelzhang/node-fs-sync#3]
Hello,

I tried using your copy() method and noticed it doesn't copy binary data correctly.

My source file (a jpg), starts with:
0000000: ffd8 ffe1 2ba1 4578 6966 0000 4949 2a00  ....+.Exif..II*.
0000010: 0800 0000 0300 1a01 0500 0100 0000 3200  ..............2.

The copied file had a bunch of bytes prepended to it:
0000000: efbf bdef bfbd efbf bdef bfbd 2bef bfbd  ............+...
0000010: 4578 6966 0000 4949 2a00 0800 0000 0300  Exif..II*.......

Cheers,
Alex

**Comment by xgvargas** [comment]
The same in here (but with webfonts instead of image).

Any solution for this issue?
