### ISSUE TITLE
fs.copy corrupts binary files

### ISSUE THREAD

**Issue by StreetStrider** [kaelzhang/node-fs-sync#4]
Hi.
Subj. It looks like `fs.copy` deals something to file content, or treat it as plain text maybe (?).
I was using `fs.copy` as a part of one of my simple build pipelines and then discovered this when I copy my assets. Fallbacked to another tool, but it asynchronous. However, I would like to proceed using `fs-sync`. It this issue in scope of this package?

**Comment by StreetStrider** [comment]
Oh, sorry, this is a dup for #3. But I'm seeing this on latest release :(

**Comment by kaelzhang** [comment]
Im sorry it is a very old node.js package of mine.

It was mainly used to copy text files, so I removes the BOM header of each file when copying.

Could you please install a new version and try again to see if it's ok now?

**Comment by StreetStrider** [comment]
Thanks, I'll stick to your module. It's good for two things:
1. it is synchronous
2. it has a sane API
Both of which making it perfect for scripting. :+1: 
I'm using it very often instead of `fs`, along with my [rootpath](https://github.com/StreetStrider/rootpath).

**Comment by kaelzhang** [comment]
Glad that you like it :smile:
